apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb-rs
  namespace: mongodb
spec:
  members: 3
  type: ReplicaSet
  version: "8.0.20"

  security:
    authentication:
      modes:
        - SCRAM

  users:
    - name: admin
      db: admin
      passwordSecretRef:
        name: mongodb-root-password
      roles:
        - name: root
          db: admin
      scramCredentialsSecretName: mongodb-rs-admin-scram

    - name: gw-ipinfo-app
      db: gw_ipinfo_nginx
      passwordSecretRef:
        name: gw-ipinfo-app-password
      roles:
        - name: readWrite
          db: gw_ipinfo_nginx
      scramCredentialsSecretName: mongodb-rs-gw-ipinfo-app-scram

  statefulSet:
    spec:
      serviceName: mongodb-rs-svc
      selector:
        matchLabels:
          app.kubernetes.io/name: mongodb-rs
          app.kubernetes.io/component: mongod
      template:
        metadata:
          labels:
            app.kubernetes.io/name: mongodb-rs
            app.kubernetes.io/component: mongod
            app.kubernetes.io/part-of: gw-ipinfo-stack
        spec:
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: mongodb-rs
                  app.kubernetes.io/component: mongod

          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchLabels:
                      app.kubernetes.io/name: mongodb-rs
                      app.kubernetes.io/component: mongod
                  topologyKey: kubernetes.io/hostname

      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            storageClassName: mongodb-efs-us
            accessModes:
              - ReadWriteMany
            resources:
              requests:
                storage: 100Gi

        - metadata:
            name: logs-volume
          spec:
            storageClassName: mongodb-efs-us
            accessModes:
              - ReadWriteMany
            resources:
              requests:
                storage: 20Gi