apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: global-googleplay-luodiye
  namespace: area
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: global-googleplay-luodiye
