apiVersion: v1
kind: Secret
metadata:
  name: gw-ipinfo-nginx-secret
  namespace: area
type: Opaque
stringData:
  IPINFO_TOKEN: "replace-me"
  TELEGRAM_BOT_TOKEN: "replace-me"
  TELEGRAM_CHAT_ID: "replace-me"
  MONGO_URI: "mongodb://gw-ipinfo-app:replace-me@mongodb-rs-svc.mongodb.svc.cluster.local:27017/gw_ipinfo_nginx?authSource=gw_ipinfo_nginx&replicaSet=mongodb-rs"
